import SwiftUI
import SwiftData
import PhotosUI

struct MilestoneItem: Identifiable {
    let id = UUID()
    let icon: String
    let title: String
    let date: Date
    let isAutoGenerated: Bool
    let usesSystemImage: Bool

    init(icon: String, title: String, date: Date, isAutoGenerated: Bool, usesSystemImage: Bool = false) {
        self.icon = icon
        self.title = title
        self.date = date
        self.isAutoGenerated = isAutoGenerated
        self.usesSystemImage = usesSystemImage
    }
}

struct MilestonesView: View {
    let milestones: [MilestoneItem]
    let memories: [Memory]
    let coupleID: String
    @Environment(AppState.self) private var appState
    @State private var showAddMemory = false

    var body: some View {
        VStack(alignment: .leading, spacing: SakinahSpacing.xl) {
            milestonesSection
            memoriesSection
        }
        .sheet(isPresented: $showAddMemory) {
            AddMemorySheet(coupleID: coupleID)
                .presentationDetents([.medium, .large])
                .presentationDragIndicator(.visible)
        }
    }

    private var milestonesSection: some View {
        VStack(alignment: .leading, spacing: SakinahSpacing.md) {
            Text("MILESTONES")
                .font(SakinahFont.captionBold)
                .tracking(0.4)
                .foregroundStyle(SakinahColor.textSecondary)
                .padding(.horizontal, SakinahSpacing.base)

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: SakinahSpacing.md) {
                    if milestones.isEmpty {
                        milestonePlaceholder
                    } else {
                        ForEach(milestones) { milestone in
                            milestoneCard(milestone)
                        }
                    }
                }
                .padding(.horizontal, SakinahSpacing.base)
                .scrollTargetLayout()
            }
            .scrollTargetBehavior(.viewAligned)
        }
    }

    private var memoriesSection: some View {
        VStack(alignment: .leading, spacing: SakinahSpacing.md) {
            HStack {
                Text("MEMORIES")
                    .font(SakinahFont.captionBold)
                    .tracking(0.4)
                    .foregroundStyle(SakinahColor.textSecondary)

                Spacer()

                Button {
                    HapticEngine.shared.fire(.tap)
                    if appState.hasPremiumAccess {
                        showAddMemory = true
                    } else {
                        appState.presentPaywall(for: .sharedSpace)
                    }
                } label: {
                    HStack(spacing: SakinahSpacing.xs) {
                        Text("Add")
                        Image(systemName: "plus")
                    }
                    .font(SakinahFont.captionBold)
                    .foregroundStyle(SakinahColor.primary)
                }
            }
            .padding(.horizontal, SakinahSpacing.base)

            if memories.isEmpty {
                SakinahCard {
                    HStack(spacing: SakinahSpacing.md) {
                        Image(systemName: "photo.on.rectangle")
                            .font(.system(size: 24, weight: .regular))
                            .foregroundStyle(SakinahColor.textTertiary)
                        Text("Add the moments you want to remember together.")
                            .font(SakinahFont.bodySmall)
                            .foregroundStyle(SakinahColor.textSecondary)
                    }
                }
                .padding(.horizontal, SakinahSpacing.base)
            } else {
                LazyVGrid(
                    columns: [
                        GridItem(.flexible(), spacing: SakinahSpacing.md),
                        GridItem(.flexible(), spacing: SakinahSpacing.md)
                    ],
                    spacing: SakinahSpacing.md
                ) {
                    ForEach(memories) { memory in
                        memoryTile(memory)
                    }
                }
                .padding(.horizontal, SakinahSpacing.base)
            }
        }
    }

    private var milestonePlaceholder: some View {
        VStack(alignment: .leading, spacing: SakinahSpacing.xs) {
            Image(systemName: "sparkles")
                .font(.system(size: 20))
                .foregroundStyle(SakinahColor.accent)
            Text("Keep showing up")
                .font(SakinahFont.captionBold)
                .foregroundStyle(SakinahColor.textPrimary)
            Text("Milestones will appear here.")
                .font(SakinahFont.caption)
                .foregroundStyle(SakinahColor.textSecondary)
        }
        .padding(SakinahSpacing.md)
        .frame(width: 120, height: 88, alignment: .leading)
        .background(SakinahColor.surfaceWarm)
        .clipShape(.rect(cornerRadius: SakinahRadius.medium))
    }

    private func milestoneCard(_ milestone: MilestoneItem) -> some View {
        VStack(alignment: .leading, spacing: SakinahSpacing.xs) {
            Group {
                if milestone.usesSystemImage {
                    Image(systemName: milestone.icon)
                        .font(.system(size: 20, weight: .regular))
                } else {
                    Image(systemName: "sparkles")
                        .font(.system(size: 20, weight: .regular))
                }
            }
            .foregroundStyle(SakinahColor.accent)

            Text(milestone.title)
                .font(SakinahFont.captionBold)
                .foregroundStyle(SakinahColor.textPrimary)
                .lineLimit(2)
                .minimumScaleFactor(0.82)

            Text(DateFormatting.gregorian(milestone.date, style: .short))
                .font(SakinahFont.caption)
                .foregroundStyle(SakinahColor.textTertiary)
        }
        .padding(SakinahSpacing.md)
        .frame(width: 120, height: 88, alignment: .leading)
        .background(SakinahColor.surfaceWarm)
        .clipShape(.rect(cornerRadius: SakinahRadius.medium))
        .overlay(
            RoundedRectangle(cornerRadius: SakinahRadius.medium)
                .stroke(SakinahColor.border, lineWidth: 1)
        )
    }

    private func memoryTile(_ memory: Memory) -> some View {
        VStack(alignment: .leading, spacing: SakinahSpacing.sm) {
            ZStack {
                if let photoData = memory.photoData, let uiImage = UIImage(data: photoData) {
                    Image(uiImage: uiImage)
                        .resizable()
                        .scaledToFill()
                } else {
                    SakinahColor.primaryLight
                    Image(systemName: "quote.opening")
                        .font(.system(size: 24, weight: .regular))
                        .foregroundStyle(SakinahColor.primary.opacity(0.55))
                }
            }
            .aspectRatio(1, contentMode: .fit)
            .clipShape(.rect(cornerRadius: SakinahRadius.medium))

            Text(memory.caption)
                .font(SakinahFont.caption)
                .foregroundStyle(SakinahColor.textPrimary)
                .lineLimit(2)
        }
    }
}

struct AddMemorySheet: View {
    @Environment(AppState.self) private var appState
    let coupleID: String
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss

    @State private var caption: String = ""
    @State private var selectedDate: Date = Date()
    @State private var selectedPhoto: PhotosPickerItem? = nil
    @State private var photoData: Data? = nil

    var body: some View {
        NavigationStack {
            VStack(spacing: SakinahSpacing.lg) {
                PhotosPicker(selection: $selectedPhoto, matching: .images) {
                    ZStack {
                        if let photoData, let uiImage = UIImage(data: photoData) {
                            Image(uiImage: uiImage)
                                .resizable()
                                .scaledToFill()
                                .frame(height: 160)
                                .clipShape(.rect(cornerRadius: SakinahRadius.medium))
                        } else {
                            VStack(spacing: SakinahSpacing.sm) {
                                Image(systemName: "photo.badge.plus")
                                    .font(.system(size: 32))
                                    .foregroundStyle(SakinahColor.primary)
                                Text("Add a photo")
                                    .font(SakinahFont.bodySmall)
                                    .foregroundStyle(SakinahColor.textSecondary)
                            }
                            .frame(maxWidth: .infinity)
                            .frame(height: 160)
                            .background(SakinahColor.backgroundSecondary)
                            .clipShape(.rect(cornerRadius: SakinahRadius.medium))
                        }
                    }
                }
                .onChange(of: selectedPhoto) { _, item in
                    Task {
                        if let data = try? await item?.loadTransferable(type: Data.self) {
                            photoData = data
                        }
                    }
                }

                TextField("Write a caption...", text: $caption, axis: .vertical)
                    .font(SakinahFont.body)
                    .padding(SakinahSpacing.md)
                    .background(SakinahColor.backgroundSecondary)
                    .clipShape(.rect(cornerRadius: SakinahRadius.medium))
                    .lineLimit(3)

                DatePicker("Date", selection: $selectedDate, displayedComponents: .date)
                    .font(SakinahFont.body)
                    .tint(SakinahColor.primary)

                Spacer()

                SakinahButton(title: "Save Memory") {
                    saveMemory()
                }
                .disabled(caption.isEmpty)
                .opacity(caption.isEmpty ? 0.55 : 1)
            }
            .padding(SakinahSpacing.base)
            .navigationTitle("New Memory")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                        .foregroundStyle(SakinahColor.primary)
                }
            }
        }
    }

    private func saveMemory() {
        guard appState.hasPremiumAccess else {
            appState.presentPaywall(for: .sharedSpace)
            dismiss()
            return
        }
        let memory = Memory(
            coupleID: coupleID,
            caption: caption,
            photoData: photoData,
            date: selectedDate
        )
        modelContext.insert(memory)
        try? modelContext.save()
        HapticEngine.shared.fire(.success)
        Task {
            await CloudKitService.shared.syncIfPossible(appState: appState, context: modelContext)
        }
        dismiss()
    }
}
