import SwiftUI
import SwiftData
import PhotosUI

struct MilestoneItem: Identifiable {
    let id = UUID()
    let icon: String
    let title: String
    let date: Date
    let isAutoGenerated: Bool
    let usesSystemImage: Bool

    init(icon: String, title: String, date: Date, isAutoGenerated: Bool, usesSystemImage: Bool = false) {
        self.icon = icon
        self.title = title
        self.date = date
        self.isAutoGenerated = isAutoGenerated
        self.usesSystemImage = usesSystemImage
    }
}

struct MilestonesView: View {
    let milestones: [MilestoneItem]
    let memories: [Memory]
    let coupleID: String
    @Environment(\.modelContext) private var modelContext
    @State private var showAddMemory = false

    var body: some View {
        VStack(alignment: .leading, spacing: SakinahSpacing.md) {
            Text("Milestones & Memories")
                .font(SakinahFont.captionBold)
                .foregroundStyle(SakinahColor.textSecondary)
                .tracking(0.4)
                .textCase(.uppercase)
                .padding(.horizontal, SakinahSpacing.base)

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: SakinahSpacing.md) {
                    // Milestone cards
                    ForEach(milestones) { milestone in
                        milestoneCard(milestone)
                    }

                    // Memory cards
                    ForEach(memories) { memory in
                        memoryCard(memory)
                    }

                    // Add memory card
                    addMemoryCard
                }
                .padding(.horizontal, SakinahSpacing.base)
                .scrollTargetLayout()
            }
            .scrollTargetBehavior(.viewAligned)
        }
        .sheet(isPresented: $showAddMemory) {
            AddMemorySheet(coupleID: coupleID)
                .presentationDetents([.medium])
        }
    }

    private func milestoneCard(_ milestone: MilestoneItem) -> some View {
        VStack(spacing: SakinahSpacing.md) {
            Spacer()
            Group {
                if milestone.usesSystemImage {
                    Image(systemName: milestone.icon)
                        .font(.system(size: 30, weight: .semibold))
                        .foregroundStyle(SakinahColor.accent)
                } else {
                    Text(milestone.icon)
                        .font(.system(size: 36))
                }
            }
            Text(milestone.title)
                .font(SakinahFont.title3)
                .foregroundStyle(SakinahColor.textPrimary)
                .multilineTextAlignment(.center)
            Text(DateFormatting.gregorian(milestone.date, style: .short))
                .font(SakinahFont.caption)
                .foregroundStyle(SakinahColor.textTertiary)
            Spacer()
        }
        .frame(width: 280, height: 160)
        .background(
            RadialGradient(
                colors: [SakinahColor.accentLight, SakinahColor.surface],
                center: .center,
                startRadius: 0,
                endRadius: 140
            )
        )
        .clipShape(.rect(cornerRadius: SakinahRadius.large))
        .sakinahShadow(.subtle)
    }

    private func memoryCard(_ memory: Memory) -> some View {
        VStack(spacing: 0) {
            if let photoData = memory.photoData, let uiImage = UIImage(data: photoData) {
                Image(uiImage: uiImage)
                    .resizable()
                    .scaledToFill()
                    .frame(width: 280, height: 96)
                    .clipped()
            } else {
                ZStack {
                    SakinahColor.primaryLight
                    Image(systemName: "photo")
                        .font(.system(size: 24))
                        .foregroundStyle(SakinahColor.primary.opacity(0.5))
                }
                .frame(width: 280, height: 96)
            }

            VStack(alignment: .leading, spacing: 4) {
                Text(memory.caption)
                    .font(SakinahFont.bodySmall)
                    .foregroundStyle(SakinahColor.textPrimary)
                    .lineLimit(2)
                Text(DateFormatting.gregorian(memory.date, style: .short))
                    .font(SakinahFont.caption)
                    .foregroundStyle(SakinahColor.textTertiary)
            }
            .padding(SakinahSpacing.md)
            .frame(width: 280, alignment: .leading)
        }
        .frame(width: 280, height: 160)
        .background(SakinahColor.surface)
        .clipShape(.rect(cornerRadius: SakinahRadius.large))
        .sakinahShadow(.subtle)
    }

    private var addMemoryCard: some View {
        Button {
            HapticEngine.shared.fire(.tap)
            showAddMemory = true
        } label: {
            VStack(spacing: SakinahSpacing.md) {
                Image(systemName: "camera.fill")
                    .font(.system(size: 24))
                    .foregroundStyle(SakinahColor.textTertiary)
                Text("Add a memory")
                    .font(SakinahFont.bodySmall)
                    .foregroundStyle(SakinahColor.textTertiary)
            }
            .frame(width: 280, height: 160)
            .background(Color.clear)
            .overlay(
                RoundedRectangle(cornerRadius: SakinahRadius.large)
                    .strokeBorder(style: StrokeStyle(lineWidth: 2, dash: [8, 4]))
                    .foregroundStyle(SakinahColor.textTertiary.opacity(0.4))
            )
        }
        .pressScale()
    }
}

// MARK: - Add Memory Sheet

struct AddMemorySheet: View {
    @Environment(AppState.self) private var appState
    let coupleID: String
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss

    @State private var caption: String = ""
    @State private var selectedDate: Date = Date()
    @State private var selectedPhoto: PhotosPickerItem? = nil
    @State private var photoData: Data? = nil

    var body: some View {
        NavigationStack {
            VStack(spacing: SakinahSpacing.lg) {
                // Photo picker
                PhotosPicker(selection: $selectedPhoto, matching: .images) {
                    ZStack {
                        if let photoData, let uiImage = UIImage(data: photoData) {
                            Image(uiImage: uiImage)
                                .resizable()
                                .scaledToFill()
                                .frame(height: 160)
                                .clipShape(.rect(cornerRadius: SakinahRadius.medium))
                        } else {
                            VStack(spacing: SakinahSpacing.sm) {
                                Image(systemName: "photo.badge.plus")
                                    .font(.system(size: 32))
                                    .foregroundStyle(SakinahColor.primary)
                                Text("Add a photo")
                                    .font(SakinahFont.bodySmall)
                                    .foregroundStyle(SakinahColor.textSecondary)
                            }
                            .frame(maxWidth: .infinity)
                            .frame(height: 160)
                            .background(SakinahColor.backgroundSecondary)
                            .clipShape(.rect(cornerRadius: SakinahRadius.medium))
                        }
                    }
                }
                .onChange(of: selectedPhoto) { _, item in
                    Task {
                        if let data = try? await item?.loadTransferable(type: Data.self) {
                            photoData = data
                        }
                    }
                }

                // Caption
                TextField("Write a caption...", text: $caption, axis: .vertical)
                    .font(SakinahFont.body)
                    .padding(SakinahSpacing.md)
                    .background(SakinahColor.backgroundSecondary)
                    .clipShape(.rect(cornerRadius: SakinahRadius.medium))
                    .lineLimit(3)

                // Date picker
                DatePicker("Date", selection: $selectedDate, displayedComponents: .date)
                    .font(SakinahFont.body)
                    .tint(SakinahColor.primary)

                Spacer()

                SakinahButton(title: "Save Memory") {
                    saveMemory()
                }
                .disabled(caption.isEmpty)
                .opacity(caption.isEmpty ? 0.55 : 1)
            }
            .padding(SakinahSpacing.base)
            .navigationTitle("New Memory")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                        .foregroundStyle(SakinahColor.primary)
                }
            }
        }
    }

    private func saveMemory() {
        let memory = Memory(
            coupleID: coupleID,
            caption: caption,
            photoData: photoData,
            date: selectedDate
        )
        modelContext.insert(memory)
        try? modelContext.save()
        HapticEngine.shared.fire(.success)
        Task {
            await CloudKitService.shared.syncIfPossible(appState: appState, context: modelContext)
        }
        dismiss()
    }
}
