import SwiftUI
import SwiftData

@Observable
@MainActor
final class UsViewModel {
    var gardenState: GardenState = GardenState()
    var daysTogether: Int = 0
    var milestones: [MilestoneItem] = []
    var selectedPlant: GardenDimension? = nil
    var showReflection: Bool = false
    var weeklyLevels: [GardenDimension: [Double]] = [:]

    func load(appState: AppState, context: ModelContext) {
        guard let couple = appState.currentCouple else { return }

        gardenState = couple.gardenState
        daysTogether = couple.daysTogether

        computeMilestones(couple: couple)
        checkReflectionNeeded(couple: couple, userID: appState.currentUser?.id ?? "", context: context)
        loadWeeklyTrends(coupleID: couple.id, userID: appState.currentUser?.id ?? "", context: context)
    }

    private func computeMilestones(couple: Couple) {
        var items: [MilestoneItem] = []
        let days = couple.daysTogether
        let createdAt = couple.createdAt

        // Day-based milestones
        let dayMilestones: [(Int, String, String)] = [
            (7, "🎉", "1 week together!"),
            (30, "🌙", "1 month together!"),
            (100, "💯", "100 days together!"),
            (180, "🌟", "6 months together!"),
            (365, "🎊", "1 year together!"),
        ]

        for (threshold, icon, title) in dayMilestones {
            if days >= threshold {
                let date = Calendar.current.date(byAdding: .day, value: threshold, to: createdAt) ?? createdAt
                items.append(MilestoneItem(icon: icon, title: title, date: date, isAutoGenerated: true))
            }
        }

        // Anniversary
        if let anniversary = couple.anniversaryDate {
            items.append(MilestoneItem(icon: "💍", title: "Anniversary", date: anniversary, isAutoGenerated: true))
        }

        milestones = items.sorted { $0.date > $1.date }
    }

    private func checkReflectionNeeded(couple: Couple, userID: String, context: ModelContext) {
        let cal = Calendar.current
        let today = Date()
        let weekday = cal.component(.weekday, from: today)

        // Show on Fridays (weekday 6) or if overdue
        let isFriday = weekday == 6

        // Check if already completed this week
        let weekStart = cal.dateComponents([.calendar, .yearForWeekOfYear, .weekOfYear], from: today).date ?? today
        let cid = couple.id
        let uid = userID
        let predicate = #Predicate<WeeklyReflection> { r in
            r.coupleID == cid && r.userID == uid && r.createdAt >= weekStart
        }
        let descriptor = FetchDescriptor<WeeklyReflection>(predicate: predicate)
        let existingCount = (try? context.fetchCount(descriptor)) ?? 0

        showReflection = (isFriday || weekday == 7) && existingCount == 0
    }

    private func loadWeeklyTrends(coupleID: String, userID: String, context: ModelContext) {
        let cal = Calendar.current
        let now = Date()

        for dim in GardenDimension.allCases {
            var levels: [Double] = []
            for weeksAgo in (0..<4).reversed() {
                let weekEnd = cal.date(byAdding: .weekOfYear, value: -weeksAgo, to: now) ?? now
                let weekStart = cal.date(byAdding: .weekOfYear, value: -(weeksAgo + 1), to: now) ?? now
                let cid = coupleID
                let uid = userID
                let predicate = #Predicate<WeeklyReflection> { r in
                    r.coupleID == cid && r.userID == uid && r.createdAt >= weekStart && r.createdAt < weekEnd
                }
                let descriptor = FetchDescriptor<WeeklyReflection>(predicate: predicate)
                if let reflection = try? context.fetch(descriptor).first {
                    levels.append(Double(reflection.scores[dim] ?? 0))
                } else {
                    levels.append(0)
                }
            }
            weeklyLevels[dim] = levels
        }
    }
}
